#!/usr/bin/python
import sys
# FIXME: this shall be removed in the final version
sys.path = ["/home/jkt/work/fzu/deska/src/deska/python", "/home/jkt/work/fzu/deska/_build"] + sys.path
import deska

deska.init()

def dump_everything():
    output = file("dump-of-everything", "wb")

    all_items = ["vendor", "service", "warranty_contract", "network",
                 "formfactor", "modelbox", "box", "modelextrahw", "extrahw",
                 "modelswitch", "switch", "modelhardware", "hardware_template",
                 "hardware", "virtual_hardware", "host", "interface", "event"]

    for kind in all_items:
        output.write("%s\n\n" % kind)
        for name, data in getattr(deska, kind)._all().iteritems():
            output.write("%s: %s\n" % (name, data))

dump_everything()
sys.exit(0)

for name, data in deska.hardware[deska.hardware.box == None].iteritems():
    output.write("%s\n" % name)

#output = file("all-hosts", "wb")
#for hostname, data in deska.host._all().iteritems():
#    output.write("%s: %s\n" % (hostname, data.service))
