#!/usr/bin/python
import sys
import time
t0 = time.time()
# FIXME: this shall be removed in the final version
sys.path = ["/home/jkt/work/fzu/deska/src/deska/python", "/home/jkt/work/fzu/deska/_build"] + sys.path
import deska

deska.init()

def dump_everything():
    output = file("dump-of-everything", "wb")

    all_items = ["vendor", "service", "warranty_contract", "network",
                 "formfactor", "modelbox", "box", "modelextrahw", "extrahw",
                 "modelswitch", "switch", "modelhardware", "hardware_template",
                 "hardware", "virtual_hardware", "host", "interface", "event"]

    t1 = time.time()
    for kind in all_items:
        t2 = time.time()
        cnt = 0
        for name, data in getattr(deska, kind)._all().iteritems():
            cnt += 1
            pass
        output.write("# Downloading %s: %d items, %ss\n" % (kind, cnt, time.time() - t2))

    t3 = time.time()
    output.write("# Total time: %ss (init: %s, run: %s)\n\n" %
                 (t3 - t0, t1 - t0, t3 - t1))

dump_everything()
