#!/bin/bash

# FIXME: this one requires running X, so it shall be switched to the Xvfb asap
# FIXME: also fix the path...

echo "DeskaDividedBox /home/jkt/work/fzu/deska/scripts/qml/DeskaDividedBox.qml" > qmldir

../../../src/qml2image/qml2image boxes.qml boxes.png
exit $?
