#!/usr/bin/python
import sys
import time
# FIXME: this shall be removed in the final version
sys.path = ["/home/jkt/work/fzu/deska/src/deska/python", "/home/jkt/work/fzu/deska/_build"] + sys.path
import deska

deska.init()

t1 = time.time()
#hosts = deska.host[(deska.service != [])]
all_services = deska.service._all()
t2 = time.time()

f_cf_groups = file("cfengine-groups.cf", "wb")
for service in all_services.keys():
    hosts = deska.host[deska.host.service.contains(service)]
    f_cf_groups.write("%s = (%s)\n" % (service, " ".join(sorted(hosts.keys()))))
f_cf_groups.close()


t3 = time.time()

file("__timing-stats", "ab").write(
    "services: total %s, main query %s, loop %s\n" % (t3 - t1, t2 - t1, t3 - t2))
