#!/bin/bash

function die() {
    echo "Die: $1" >&2
    exit 1
}

# Prepare a "script" which consults our env variable for the actual commands
cat > ${DESKA_CFGGEN_SCRIPTS}/01-doit.sh <<EOF
#!/bin/bash
eval "\${MYCMD}"
EOF
chmod +x ${DESKA_CFGGEN_SCRIPTS}/01-doit.sh
cp -a ${DESKA_CFGGEN_SCRIPTS}/0{1,2}-doit.sh
sed -i 's:MYCMD:MYCMD2:' ${DESKA_CFGGEN_SCRIPTS}/02-doit.sh


MY_WC="${DESKA_CFGGEN_GIT_WC}/default"

function generate() {
    #GIT_PYTHON_TRACE=full
    python ${DESKA_SOURCES}/src/deska/LowLevelPyDeska/generators/gitgenerator.py ${DESKA_CFGGEN_GIT_PRIMARY_CLONE} ${MY_WC} ${DESKA_CFGGEN_SCRIPTS} $* || die "Test failed"
}

function verify-same() {
    rm -rf ${DESKA_CFGGEN_GIT_SECOND}
    git clone ${DESKA_CFGGEN_GIT_REPO} ${DESKA_CFGGEN_GIT_SECOND} || die "Cannot clone"
    diff -Naurt -x .git ${MY_WC} ${DESKA_CFGGEN_GIT_SECOND} || die "There are some differences"
}

function verify-files() {
    pushd "${MY_WC}"
    CONTENTS=`find . -name .git -a -type d -prune -o -name README -a -type f -prune -o -type f -print`
    if [[ x${CONTENTS} != x${1} ]]; then
        echo "Found:"
        echo "${CONTENTS}"
        echo "Expected:"
        echo "${1}"
        die "Different files"
    fi
    popd
}

function check-line-count() {
    COUNT=`wc -l "${MY_WC}/${1}" | cut -d ' ' -f 1`
    if [[ "${COUNT}" -ne "${2}" ]]; then
        die "Probably run the generators again (expected ${2} lines, got ${COUNT} lines instead)"
    fi
}


# The second script should do nothing; this will be used later
export MYCMD2=""

echo "Try to create a file and commit that change"
export MYCMD="mkdir foo; echo ahoj > foo/bar"
generate save-nonfresh
verify-same
verify-files "./foo/bar"

echo "Rewrite its contents and commit"
export MYCMD="echo bleh > foo/bar"
generate save-nonfresh
verify-same
verify-files "./foo/bar"

echo "Remove that file and commit"
export MYCMD="rm foo/bar"
generate save-nonfresh
verify-same
verify-files ""

echo "Create brand new file, execute a diff, don't save"
export MYCMD="echo blabla >> blabla"
generate diff-nonfresh
verify-files "./blabla"

echo "Execute the diff once more, don't regenerate"
generate diff-fresh
verify-files "./blabla"
check-line-count blabla 1

echo "Save the cached diff, don't regenerate"
generate save-fresh
verify-same
verify-files "./blabla"
check-line-count blabla 1

echo "diff, force generators re-run"
generate diff-nonfresh
verify-files "./blabla"
# the saved version has one line, we're told not to re-use it -> one more line
check-line-count blabla 2

echo "save, force generators re-run"
generate save-nonfresh
verify-files "./blabla"
# The WC has two lines, but we're asked to clean the WC, so it has just one line.
# Then the generators run again, and now we have two lines again.
check-line-count blabla 2

echo "Clean the repo again"
export MYCMD="rm blabla"
generate save-nonfresh
verify-same
verify-files ""

echo "Check that the scripts are executed in order"
# the first one should create that file
export MYCMD="echo blabla >> blabla"
# The second script should remove the first one's result and fail if it is not present
# We have to include something in the repo, otherwise the commit would fail with no changes to save
export MYCMD2="rm blabla; touch foo"
generate save-nonfresh
verify-same
verify-files "./foo"
